GigsNearMeAppStart/Controllers/HomeController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using AutoMapper;
using GigsNearMe.Models;
using GigsNearMe.Contracts;
using GigsNearMe.ViewModels;

namespace GigsNearMe.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IGigsNearMeRepository _repository;
        private readonly IMapper _mapper;

        public HomeController(ILogger<HomeController> logger, IGigsNearMeRepository repository, IMapper mapper)
        {
            _logger = logger;
            _repository = repository;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index()
        {
            var touringArtists = await _repository.ArtistRepository.GetArtistsWithToursAsync();

            var viewData = _mapper.Map<IEnumerable<Artist>, IEnumerable<ArtistViewModel>>(touringArtists);
            return View(viewData);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

GigsNearMeAppStart/Controllers/ToursController.cs
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.EntityFrameworkCore;
using AutoMapper;
using GigsNearMe.Contracts;
using GigsNearMe.ViewModels;
using GigsNearMe.Models;

namespace GigsNearMe.Controllers
{
    public class ToursController : Controller
    {
        private readonly ILogger<ToursController> _logger;
        private readonly IGigsNearMeRepository _repository;
        private readonly IMapper _mapper;

        public ToursController(ILogger<ToursController> logger, IGigsNearMeRepository repository, IMapper mapper)
        {
            _logger = logger;
            _repository = repository;
            _mapper = mapper;
        }

        // GET: Tours
        public async Task<IActionResult> Index(string sortOrder)
        {
            ViewData["NameSortParm"] = string.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["DateSortParm"] = sortOrder == "Date" ? "date_desc" : "Date";

            var tours = _repository.TourRepository.FindAll();

            switch (sortOrder)
            {
                case "name_desc":
                    tours = tours.OrderByDescending(t => t.Name);
                    break;
                case "Date":
                    tours = tours.OrderBy(t => t.Start);
                    break;
                case "date_desc":
                    tours = tours.OrderByDescending(t => t.Start);
                    break;
                default:
                    tours = tours.OrderBy(t => t.Name);
                    break;
            }

            var viewData = _mapper.Map<IEnumerable<Tour>, IEnumerable<TourViewModel>>(await tours.ToListAsync());
            return View(viewData);
        }

        // GET: Tours/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || !id.HasValue)
            {
                return NotFound();
            }

            var tour = await _repository.TourRepository.GetTourDetailsAsync(id.Value);
            if (tour == null)
            {
                return NotFound();
            }

            return View(_mapper.Map<TourViewModel>(tour));
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

    }
}

GigsNearMeAppStart/Views/Home/Index.cshtml
@model IEnumerable<ArtistViewModel>

@{
    ViewBag.Title = "GigsNearMe! Home";
}

<h3>Upcoming Tours!</h3>

<div class="upcoming-tours-list">

    @foreach (var item in Model)
    {
        <div class="row offset-sm-1 justify-content-start align-items-start">

            <div class="col-3">
                <h4>@item.Name</h4>
            </div>

            <div class="col-9">
                <div class="card-deck">
                    @foreach (var tour in item.Tours)
                    {
                    <div class="col-sm-6">
                        <div class="card bg-light mb-3">
                            <div class="card-body">
                                <h5 class="card-title">@tour.Name</h5>
                                <p class="card-text">Starts @tour.Start.ToString("dddd MMMM dd, yyyy").</p>
                                @Html.ActionLink("Find out more...", "Details", "Tours", new { id = tour.TourID }, null)
                            </div>
                        </div>
                    </div>
                    }
                </div>
            </div>
        </div>
    }
</div>